### ISSUE TITLE
运行出现问题

### ISSUE THREAD

**Issue by 12334223345** [Mai-icy/Spotify-lyrics-window#10]
<img width="451" alt="eff05169a40035864b85740d08672cf" src="https://github.com/Mai-icy/Spotify-lyrics-window/assets/153687289/8af582b0-d8a4-487b-a0f2-0656d432fa00">

**Comment by Mai-icy** [comment]
你好👋，请问您是直接在压缩文件中打开的吗，请先解压到文件夹再打开对应的exe

**Comment by Mai-icy** [comment]
如还有问题，请reopen
