### ISSUE TITLE
歌词框拉伸后，阴影部分的文字显示异常

### ISSUE THREAD

**Issue by Fyime** [Mai-icy/Spotify-lyrics-window#11]
对master的代码做了一些改造，有个关于歌词阴影问题困扰了好久，希望能帮忙分析下

**背景：**
运行后鼠标点击拖动窗口，以及普通的左右键点击都是正常的，但只要按住鼠标对窗口进行拉伸，释放鼠标后，阴影部分的歌词（显示为背景的白色部分）会一直显示为鼠标释放时的那一句，不再改变（除非再拉伸窗口）。
如图所示棕色部分是正常通过`self.above_scrollArea.set_text('')`更新的歌词，白色部分是鼠标拉伸窗口释放时的那句歌词。

想请帮忙分析下，背景里的白色文字，是哪个组件控制的，大概是哪部分代码存在问题。

<img width="715" alt="image" src="https://github.com/Mai-icy/Spotify-lyrics-window/assets/46854523/7d8256e3-8409-403a-a3bd-6402660692e3">

![output3](https://github.com/Mai-icy/Spotify-lyrics-window/assets/46854523/d92c8c84-6a5b-4860-860a-9c0b967c491b)

**Comment by Mai-icy** [comment]
原本的歌词窗口是依靠`below_scrollArea`和`above_scrollArea`来实现的，请问您有考虑过below_scrollArea吗

**Comment by Mai-icy** [comment]
https://github.com/Mai-icy/Spotify-lyrics-window/blob/bb4aa087d2d1ee35ba43487c74aac662e0b2514f/SpotifyLyricWindow/view/lyric_window/lyrics_window_view.py#L366
可能跟这里的update相关，您可以看看
至于为什么只有在row==1的时候update已经记不清了，您可以试着改改看

**Comment by Fyime** [comment]
我再排查下试试，感觉像是哪个地方状态没更新，或者是底层的文字被当成固定样式了

大佬这个界面用起来体验很👍，核心功能都挺完善的，我这边自己加点东西也很方便哈哈

话说有考虑过与Spotify解绑吗？我这边是利用这个开源项目，通过调用外部命令行程序获取系统级别正在播放的歌曲“标题”、“作者”、“持续时间”、“播放进度”信息，对网易云的播客声音、和一些通过视频播放器播放的mv帮助很大
https://github.com/kirtan-shah/nowplaying-cli
再就是我这边想搞个搜索歌词的对话框/功能，像播客/视频这种，标题很多都是不规范的，需要提供给用户自行编辑搜索内容和选择绑定的能力

**Comment by Mai-icy** [comment]
本项目也包含了歌词搜索下载的功能，也可以看看（之前也有单独的项目做了这个功能）

这个项目吃了很多pyqt的坑，在dev-fluent-pyqt分支里面尝试使用新UI的时候遇到了个人解决不了的问题，该项目也就停滞了。
和spotify的解绑是个非常不错的思路，本人对于开发开源项目的经验实在不足，不知道如何提供出利于他人兼容使用的单独歌词窗口项目。希望能互相交流。

（可以加我qq交流：244095602）
