### ISSUE TITLE
请求增加spotify歌词api

### ISSUE THREAD

**Issue by venovoz** [Mai-icy/Spotify-lyrics-window#13]
首先感谢作者！
使用的版本的是v1.2，人在国外，client id, secret设置都通过了。打开.exe会显示searching for lyric， 然后就闪退。确认过不是杀毒软件，也尝试使用管理员身份运行。会是因为在网易搜索歌词的时候被墙了吗？
再次感谢！

**Comment by Mai-icy** [comment]
有很大可能，在国外访问酷狗或者网易云的api大概率连不上，会出现以上情况

**Comment by Mai-icy** [comment]
我暂时没有其它歌词api的方案，您可以做出推荐

**Comment by venovoz** [comment]
也许可以直接使用Spotify获取歌词的api？Musixmatch，来直接获取歌词，虽然不是很全
https://github.com/akashrchandran/spotify-lyrics-api
感谢回复！

**Comment by Mai-icy** [comment]
感谢建议，会在之后参考添加

**Comment by Mai-icy** [comment]
add at https://github.com/Mai-icy/Spotify-lyrics-window/commit/1f162b973c117787368341e5e0c21103a122cab4
之后发布release

**Comment by Mai-icy** [comment]
release at [v1.3](https://github.com/Mai-icy/Spotify-lyrics-window/releases/tag/v1.3)

**Comment by venovoz** [comment]
太强了！！！但是还是遇到了秒退的问题。可能是因为spotify的min_score不够高导致还是使用了酷狗的api，或者是比较的时候还是需要调用酷狗的api导致秒退？也许可以增加一个选项让用户自己选择一个强制api或者使用多方比较的默认设置。爆炸感谢！！！

**Comment by Mai-icy** [comment]
其它api的调用都加了错误捕捉，导致崩溃应该是其他原因，我也有尝试，但是debug的时候就是不会复现，我还在调试。至于添加选择，由于需要修改ui，所以暂时推到后面

**Comment by Mai-icy** [comment]
目前代码的逻辑是，走kugou+网易云，如果不够分或者请求错误，就走spotify，而且spotify没有分数，有的时候会请求错误，还在排查

**Comment by venovoz** [comment]
明白了，感谢大佬解答！

**Comment by Mai-icy** [comment]
spotify api 需要sp_dc ，通过主动抓取sp_dc会导致很多问题，后续修改为在配置文件中手动添加sp_dc
sp_dc只需要在登陆的web spotify浏览器cookie中找到对应的值复制即可，有效期到网页端注销登录为止。

**Comment by venovoz** [comment]
感谢感谢！以下是反馈：
手动添加sp_dc后还是会在歌词框显示“searching for lyric"的时候闪退。
而且如果不打开桌面端spotify的时候，点击”用户授权“按钮会弹出网页并且显示授权成功和”no user active"，然后再打开spotify仍然显示”no user active"。只有在先打开spotify的时候再点击”用户授权“按钮会弹出网页并且显示授权成功和“searching for lyric"然后闪退。

**Comment by Mai-icy** [comment]
如果没有在播放音乐，就是no user active
🤔我现在有点怀疑是不是没有文件读写权限导致的，可以尝试使用管理员运行

**Comment by venovoz** [comment]
感谢！尝试了使用管理员运行：
如果先打开spotify但并不播放音乐，然后再用管理员身份运行“main”，可以直接显示“searching for lyric"，然后闪退。
如果先用管理员身份运行“main”，再打开spotify并播放音乐，仍会一直显示”no user active"，直到点击”用户授权“或“校准歌词”，然后显示“searching for lyric"加闪退。
