### ISSUE TITLE
驗證賬號之後開始播放程序崩潰

### ISSUE THREAD

**Issue by SugarB1ade** [Mai-icy/Spotify-lyrics-window#15]
如題

**Comment by Mai-icy** [comment]
请问能弹出edge浏览器验证吗

**Comment by Mai-icy** [comment]
fix at https://github.com/Mai-icy/Spotify-lyrics-window/commit/56be41e0cff4c67d45b65dc949e618e2ca9f234d

**Comment by SugarB1ade** [comment]
> 请问能弹出edge浏览器验证吗

有

**Comment by Mai-icy** [comment]
已修复，等待后续打包

**Comment by Mai-icy** [comment]
已发布新release

**Comment by mohdlatif** [comment]
It keeps crashing after verification, I have python 12 installed, win 11 23h2 x64. 
After I click the user icon, it crashes

**Comment by Mai-icy** [comment]
> It keeps crashing after verification, I have python 12 installed, win 11 23h2 x64. After I click the user icon, it crashes

im sorry, can you see the Edge Browser window?

**Comment by mohdlatif** [comment]
> > It keeps crashing after verification, I have python 12 installed, win 11 23h2 x64. After I click the user icon, it crashes
> 
> im sorry, can you see the Edge Browser window?

Yes, and I logged with my username and password, An English interface seems like will help navigate the settings, I keep spend some time between capturing and translating.

Here is the history list 

![image](https://github.com/Mai-icy/Spotify-lyrics-window/assets/56746772/62ac56a1-37b3-455f-af12-52cbb424585a)


BTW, can this tool show the Transcript text from Spotify ?
![image](https://github.com/Mai-icy/Spotify-lyrics-window/assets/56746772/25278c56-c11e-4238-80de-47a323a3e5a0)

**Comment by Mai-icy** [comment]
It looks like you logged in successfully
maybe it was a crash for something else.

this tool gain the lyric from Musixmatch of spotify.I'm not sure it can work.
and this tool does not capture anything other than the song.
I haven't done this feature yet.

**Comment by SugarB1ade** [comment]
> 已发布新release

還是發生同樣的問題
我win11 pro 23H2

**Comment by Mai-icy** [comment]
> > 已发布新release
> 
> 
> 
> 還是發生同樣的問題
> 
> 我win11 pro 23H2

token文件是否存在，配置文件setting.toml里面有没有spdc的值

播放的音频文件是否是音乐

**Comment by XiyangZatPoliTo** [comment]
我也是这个问题，刚刚下载了最新的release，依然是在搜索歌词的过程中之间程序崩溃，然后闪退，系统为win10

**Comment by SugarB1ade** [comment]
沒有spdc的值

**Comment by SugarB1ade** [comment]
> > > 已发布新release
> > 
> > 
> > 還是發生同樣的問題
> > 我win11 pro 23H2
> 
> token文件是否存在，配置文件setting.toml里面有没有spdc的值
> 
> 播放的音频文件是否是音乐

沒有spdc的值

**Comment by Mai-icy** [comment]
fix at https://github.com/Mai-icy/Spotify-lyrics-window/commit/e591f695a661e3173efe628f7ba28144150e5a93

**Comment by Mai-icy** [comment]
已发布新release

**Comment by Mai-icy** [comment]
> > fix at [e591f69](https://github.com/Mai-icy/Spotify-lyrics-window/commit/e591f695a661e3173efe628f7ba28144150e5a93)
> 
> release 1.5 on win 23h2, still crash. 若在crash开始的两秒内狂点 account icon，可以打开浏览器，但标签页内无内容。 与此同时，悬浮窗显示端口8888被占用 *已排查8888端口未被占用 *setting.toml 没有sp_dc值

1.登陆client id secret，提示成功验证client
2.提示用户验证后只点一次 后等待页面生成(可能需要代理)，登陆spo账户并进行授权
在哪一步或者中间出现崩溃
sp_dc已不再收集
没有限制验证按钮点击，多次点击会显示占用

**Comment by SRaccy** [comment]
按照提示進行驗證時，Spotify授權頁面能正常加載
但點擊授權後會進入無止境的loading，關閉網頁後提示"no user active"
若再次點擊用戶圖示，則不會再正常加載Spotify頁面
win10 22H2, firefox

**Comment by Mai-icy** [comment]
no user active表面已经成功绑定，用户并没有在播放音乐

> 按照提示進行驗證時，Spotify授權頁面能正常加載 但點擊授權後會進入無止境的loading，關閉網頁後提示"no user active" 若再次點擊用戶圖示，則不會再正常加載Spotify頁面 win10 22H2, firefox

**Comment by SRaccy** [comment]
> no user active表面已经成功绑定，用户并没有在播放音乐
> 
> > 按照提示進行驗證時，Spotify授權頁面能正常加載 但點擊授權後會進入無止境的loading，關閉網頁後提示"no user active" 若再次點擊用戶圖示，則不會再正常加載Spotify頁面 win10 22H2, firefox

因此前經歷了多次崩潰，以為是錯誤代碼，把Spotify上的app刪除了，只能重新驗證
重新解壓縮了程式，按照說明建立新的app並再次驗證，但又再次崩潰
1. client驗證正常
2. 點擊了1次用戶圖示，Spotify頁面能正常加載
3. 點擊同意，進入Loading
4. 等待一段時間後關閉頁面，顯示no user active
5. 播放音樂，點擊校準歌詞，顯示searching for lyrics，一秒後崩潰

**Comment by Mai-icy** [comment]
扩大了错误捕捉，增加日志。
预计出现问题后不会崩溃，可以将日志内容发出来

**Comment by Mai-icy** [comment]
> 扩大了错误捕捉，增加日志。 预计出现问题后不会崩溃，可以将日志内容发出来

已打包发布

**Comment by Mai-icy** [comment]
可以分享一下出现下面这个问题的时候播放的曲目吗

**Comment by Mai-icy** [comment]
我无法复现，请问其他歌曲也会遇到这个问题吗

**Comment by Mai-icy** [comment]
我了解了，是由于网易云的api认定你在国外，返回的数据值我第一次遇到，并没有做判断

**Comment by Mai-icy** [comment]
已打包发布

**Comment by Mai-icy** [comment]
和之前的原因同理，在国外无法使用国内酷狗音乐的元数据API
因为没遇到过所以没有做特殊处理

**Comment by Mai-icy** [comment]
该问题已解决
