### ISSUE TITLE
可以告知代理网站域名以及如何展示敏感词

### ISSUE THREAD

**Issue by yoshirinda** [Mai-icy/Spotify-lyrics-window#18]
如题，项目很好，但是与我使用代理会发生冲突，可以告知软件网络请求的流向吗，我加入白名单，否则总是request error。以及如何展示歌词中可能涉及到的敏感词

**Comment by Mai-icy** [comment]
可以运行一次关闭后的resource\setting.toml中的proxy_ip中配置
例如：
proxy_ip = "http://127.0.0.1:8890"

**Comment by Mai-icy** [comment]
歌词源于 酷狗 网易云 spotify的接口，暂时没有方法。

**Comment by yoshirinda** [comment]
解决了，非常感谢，再夸一次，项目很好
