### ISSUE TITLE
请问出现“请先引导用户完成验证”怎么解决

### ISSUE THREAD

**Issue by zhaohanyun** [Mai-icy/Spotify-lyrics-window#2]
client id和scret已经填好了

**Comment by Vltever** [comment]
![s](https://user-images.githubusercontent.com/87631580/227450520-29839341-acd6-4ed4-a148-7d36b56d8d87.png)
按左边第二个按钮

**Comment by Mai-icy** [comment]
是否已经解决，若已解决请自行`Reopen`
