### ISSUE TITLE
用户验证

### ISSUE THREAD

**Issue by kle1n2** [Mai-icy/Spotify-lyrics-window#20]
引导用户完成验证的操作在哪？

**Comment by Mai-icy** [comment]
在歌词窗口上面有个人形图标的按钮

**Comment by Mai-icy** [comment]
从右往左第二个

**Comment by kle1n2** [comment]
验证后程序会闪退

**Comment by Mai-icy** [comment]
该问题仍在排查，在部分用户会遇到

**Comment by Mai-icy** [comment]
请问能弹出edge浏览器验证吗

**Comment by kle1n2** [comment]
> 请问能弹出edge浏览器验证吗

可以的

**Comment by Mai-icy** [comment]
token文件是否存在，配置文件setting.toml里面有没有spdc的值

**Comment by kle1n2** [comment]
> token文件是否存在，配置文件setting.toml里面有没有spdc的值
setting.toml里面没找到spdc的值（好几天没上github 回复的有点慢..

**Comment by Mai-icy** [comment]
ok，已了解

**Comment by Mai-icy** [comment]
fix at https://github.com/Mai-icy/Spotify-lyrics-window/commit/56be41e0cff4c67d45b65dc949e618e2ca9f234d

**Comment by Mai-icy** [comment]
已发布新release
