### ISSUE TITLE
根据页面完成授权，会显示无法登录

### ISSUE THREAD

**Issue by Aron001xx** [Mai-icy/Spotify-lyrics-window#21]
![image](https://github.com/Mai-icy/Spotify-lyrics-window/assets/83758425/4843c90c-7960-4b1f-8bfd-d64c44e40b3a)
![image](https://github.com/Mai-icy/Spotify-lyrics-window/assets/83758425/9de05558-9610-4cf5-8174-c7f8778ea845)

**Comment by Mai-icy** [comment]
是由于获取spdc的特殊手段，导致谷歌登录这种严格检查被禁止

**Comment by Mai-icy** [comment]
可以暂时使用v1.2版本完成登录验证后，将setting.toml和token文件替换到新版本，若没有spdc，则是用不了spotify的歌词api（非必要）

**Comment by Aron001xx** [comment]
问题解决了，在用其他邮箱绑定一下就可以登陆了😘，感谢！
