### ISSUE TITLE
8888端口被占用

### ISSUE THREAD

**Issue by XiyangZatPoliTo** [Mai-icy/Spotify-lyrics-window#22]
在进行验证的时候，浏览器闪退，软件显示8888端口被占用

**Comment by Mai-icy** [comment]
可以根据网上教程 查找并关闭占用端口的进程，验证用到的8888端口是临时使用的，验证完后可以恢复运行

**Comment by XiyangZatPoliTo** [comment]
目前端口及验证问题已经解决，但是打开软件之后，显示searching for lyric大概两秒后闪退，重开软件依然闪退

**Comment by Mai-icy** [comment]
https://github.com/Mai-icy/Spotify-lyrics-window/issues/15

**Comment by furuhata123** [comment]
您好！
我有必须在localhost:8888运行的进程，有办法在其他端口运行本程序吗？

**Comment by Mai-icy** [comment]
在https://github.com/Mai-icy/Spotify-lyrics-window/blob/main/SpotifyLyricWindow/common/api/user_api/user_auth.py#L93中设置，实际上是临时使用验证一下就可以了，也可以在其他机器上获取一遍再移动配置文件
