### ISSUE TITLE
No lyric found的問題

### ISSUE THREAD

**Issue by Chizu8216** [Mai-icy/Spotify-lyrics-window#25]
![Snipaste_2024-10-15_10-58-47](https://github.com/user-attachments/assets/2222c788-0349-4dc6-aeda-f974c8b93cd3)

可以識別到歌自動跳轉，但就是獲取不了歌詞

**Comment by Mai-icy** [comment]
那就是该歌词已经尝试搜索，匹配相似分数并没有到目标值。请打开歌词管理工具进行手动选择下载歌词，或者手动导入歌词。
填入sp_dc可以使用spotify的歌词

**Comment by Chizu8216** [comment]
> 那就是该歌词已经尝试搜索，匹配相似分数并没有到目标值。请打开歌词管理工具进行手动选择下载歌词，或者手动导入歌词。 填入sp_dc可以使用spotify的歌词

明白。手動下載歌詞是可以的，但這樣一首一首下的也是挺麻煩的
另外sp_dc是找到了，但填在哪裡呢？填在歌詞設置裡會卡在顯示 calibrating! 畫面

**Comment by Mai-icy** [comment]
填在 resoures/setting.toml 里面有个sp_dc的项

**Comment by Chizu8216** [comment]
> 填在 resoures/setting.toml 里面有个sp_dc的项

完美解決，感恩大神
