### ISSUE TITLE
client id、secret确认导入后程序崩溃

### ISSUE THREAD

**Issue by LOVEgithub12** [Mai-icy/Spotify-lyrics-window#7]
client id、secret确认导入后程序崩溃

**Comment by Mai-icy** [comment]
请问是否已经关闭全局代理

**Comment by LOVEgithub12** [comment]
> 请问关闭全局代理 未关闭全局代理是否会导致程序崩溃

没开全局，tun也关了

**Comment by LOVEgithub12** [comment]
> 请问关闭全局代理 未关闭全局代理是否会导致程序崩溃
![动画](https://github.com/Mai-icy/Spotify-lyrics-window/assets/74039645/7e5153df-379b-4e75-9412-c8f4140a99c2)

**Comment by Mai-icy** [comment]
我难以复现您遇到的问题，我只能猜测是否是代理导致的问题，因为打开dashboard需要代理，您可以先记录id和sec，重启电脑再试

**Comment by LOVEgithub12** [comment]
谢谢，我明天用我同学电脑试试。重启试过了，开机后退出clash，还是崩溃

**Comment by Mai-icy** [comment]
您可以尝试直接将client id 和 sec塞入`resource/setting.toml` 再打开

**Comment by LOVEgithub12** [comment]
> 您可以尝试直接将client id 和 sec塞入`resource/setting.toml` 再打开

在从没用过代理的电脑试了，还是崩溃；创建client有什么需要注意的吗？

**Comment by Mai-icy** [comment]
十分抱歉给你带来的不便，也感谢你的耐心，晚些时候我会注册新号进行测试，有可能是spotify的api有所更新。

**Comment by Mai-icy** [comment]
我创建了新的账号后更换电脑进行测试，还是未能复现您的问题，您可以尝试新建一个client或者换一个账号创建client
`Redirect URIs` 的内容是 `http://localhost:8888/callback` ， 请注意，用A账号创建的client想访问B账号的播放数据需要在`User`页面添加B用户

**Comment by cha0lam** [comment]
使用1.0和1.1都会遇到，具体表示是导入id和secret，经过用户验证后程序闪退，并且id和secret并没有记录在setting文件中，使用管理员运行遇到同样的问题

**Comment by Mai-icy** [comment]
您好，你遇到的问题是因为最近api更换服务器导致被墙的情况，而我的项目没有处理好走代理的情况（因为之前不用）所导致的。将会在之后更新（两者不属于一个问题

**Comment by Mai-icy** [comment]
已经检查相关问题，会在新版本添加配置文件内容手动设置代理服务器地址。

**Comment by Mai-icy** [comment]
好的，之后会进行封装

**Comment by Mai-icy** [comment]
已上传，可以运行一次关闭后在`resource\setting.toml`中的`proxy_ip`中配置
例如：
proxy_ip = "http://127.0.0.1:8890"

**Comment by Mai-icy** [comment]
client id、secret导入后错误是因为 未在[spotify dashboard](https://developer.spotify.com/dashboard)正确设置，添加用户
现已添加错误安全提醒用户，请等待新release发布

**Comment by Mai-icy** [comment]
已修复
