### ISSUE TITLE
输入client id和secret后提示“请先引导用户完成验证”

### ISSUE THREAD

**Issue by INify** [Mai-icy/Spotify-lyrics-window#8]
![Screenshot 2023-11-18 212816](https://github.com/Mai-icy/Spotify-lyrics-window/assets/61307591/4dabf286-c20b-428f-b7ec-5b4e873281f3)

该怎么解决这个问题？

**Comment by Vltever** [comment]
> ![Screenshot 2023-11-18 212816](https://user-images.githubusercontent.com/61307591/284001499-4dabf286-c20b-428f-b7ec-5b4e873281f3.png)
> 
> 该怎么解决这个问题？

![227450520-29839341-acd6-4ed4-a148-7d36b56d8d87](https://github.com/Mai-icy/Spotify-lyrics-window/assets/87631580/02dba6c9-a396-44da-8b0c-2de419230bd4)
按这个按钮
